#!/bin/bash

# run with this to get short output
# ./run_tests | grep ">>>"

function run_test() {
	echo ">>> runing test $1..."
	if ./$1 2>&1; then
		echo ">>> PASSED"
		((n_passed=n_passed+1))
	else
		echo ">>> FAILED"
		((n_failed=n_failed+1))
	fi
}

function run_t05_test() {
  echo ">>> runing t05 test $1..."
  if ./pyt05 $1 2>&1; then
    echo ">>> PASSED"
    ((n_passed=n_passed+1))
  else
    echo ">>> FAILED"
    ((n_failed=n_failed+1))
  fi
}

function run_t05_test_xfail() {
  echo ">>> runing t05 test $1 xfail..."
  if ./pyt05 $1 2>&1; then
    echo ">>> FAILED"
    ((n_failed=n_failed+1))
  else
    echo ">>> PASSED"
    ((n_passed=n_passed+1))
  fi
}

n_passed=0
n_failed=0

run_test t05_ObjectTest.py
run_test t05_StringTest.py
run_test t05_CFunctionTest.py
run_test t05_FunctionTest.py
run_test t05_BoolTest.py
run_test t05_IntegerTest.py
run_test t05_NullTest.py
run_test t05_LexerTest.py
run_test t05_InputStreamTest.py
run_test t05_NodeTest.py
run_test t05_ParserTest.py
run_test t05_AcobTest.py
run_test t05_VmTest.py

run_t05_test testsuite/test001.t05
run_t05_test testsuite/test002.t05
run_t05_test testsuite/test003.t05
run_t05_test testsuite/test004.t05
run_t05_test testsuite/test005.t05
run_t05_test testsuite/test006.t05
run_t05_test testsuite/test007.t05
run_t05_test testsuite/test008.t05
run_t05_test testsuite/test009.t05
run_t05_test testsuite/test010.t05
run_t05_test testsuite/test011.t05
run_t05_test testsuite/test012.t05
run_t05_test testsuite/test013.t05
run_t05_test testsuite/test014.t05
run_t05_test_xfail testsuite/test015.t05
run_t05_test testsuite/test016.t05
run_t05_test testsuite/test017.t05
run_t05_test testsuite/test018.t05
run_t05_test testsuite/test019.t05
run_t05_test testsuite/test020.t05
run_t05_test testsuite/test021.t05

echo ""
echo ">>> -------------------------"
echo ">>> n_passed = $n_passed"
echo ">>> n_failed = $n_failed"

